export interface IUser {
  first_name: string,
  last_name: string,
  departement: number,
  role: string,
  adress: string,
  city: string,
  birth_date: Date,
  phoneHome: number,
  phonePro: number,
  poste_id: number,
  type_employee: number,
  email: string,
  password: string,
  date_arrive: Date,
}
